runtime: php82

env_variables:
  APP_BASE_URL: "https://navirahomes.appspot.com/"
  DB_USER: cirsa
  DB_PASS: 12345@Cirsa
  DB_NAME: cirsa
  INSTANCE_UNIX_SOCKET: /cloudsql/navirahomes:asia-southeast1:cirsa

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  # Static assets (CSS, JS, images etc.)
  - url: /userassets
    static_dir: userassets

  - url: /assets
    static_dir: assets

  # Block direct access to system/ and application/
  - url: /system/.*
    script: index.php

  - url: /application/.*
    script: index.php

  # Catch-all: send everything to CodeIgniter index.php
  - url: /.*
    script: index.php
