runtime: php82

env_variables:
  APP_BASE_URL: "https://navirahomes.appspot.com/"
  DB_USER: cirsa
  DB_PASS: 12345@Cirsa
  DB_NAME: cirsa
  INSTANCE_UNIX_SOCKET: /cloudsql/navirahomes:asia-southeast1:cirsa
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50



handlers:
  - url: /userassets
    static_dir: userassets

  # - url: /.*
  #   script: auto

  - url: /.*
    script: index.php
