# cloudbuild.yaml
# Minimal Cloud Build pipeline for App Engine deploys (CodeIgniter PHP)

steps:
  # Step 1: Deploy to App Engine
  - name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "app.yaml", "--quiet"]

# Use the default Cloud Build service account
serviceAccount: "projects/navirahomes/serviceAccounts/1012736884546@cloudbuild.gserviceaccount.com"

# Avoid default logs bucket issue → force Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY






