# cloudbuild.yaml
# Minimal Cloud Build pipeline for App Engine deploys (CodeIgniter PHP)

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']
serviceAccount: '1012736884546@cloudbuild.gserviceaccount.com'
logsBucket: 'gs://navirahomes-cloudbuild-logs-1757338735'   # replace with your bucket
options:
  logging: GCS_ONLY
timeout: '1200s'





